"""
Django settings for myapp project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# STRIPE_API_KEY_PUBLISHABLE = "pk_test_51HU5jvFAyf8J0IoEy5UYKhklA8eW1XEFtetsBzTaBcWl2Sgw0SHhv4EuOZ1Zk2RZFwKKEAjHicVllCicekv66BVO00alvoahqO"
# STRIPE_API_KEY_HIDDEN = "sk_test_51HU5jvFAyf8J0IoEIwXdkhJg7FkubEcGH2SHmK33ZY04989MDkzKCecvavtIOInxdKYKpN6MUrsVxMsIHQ6FYepD00Kz7GgdXY"
#
# RAZORPAY_API_KEY_PUBLISHABLE = "rzp_test_q3wepxuqzC1Gip"
# RAZORPAY_API_KEY_HIDDEN = "ZwXFYaOcFyEzUB1gX0D85aYD"
#
# PAYPAL_API_KEY_PUBLISHABLE = "Acj6k32QQTwsGBtMaFrq-DJoe7vp8nXuurQc8mXvtFoqHZ5qMjnzfXPdwrCyMCmXZvZApD-vneXPaZ-x"
# PAYPAL_API_KEY_HIDDEN = "EL9_C9VDSAHboJddJBUit1GEMLySx6wGBFVqcTqRttpzGeKnY6epwl3cRwFt3xe02imZp8Zb386upG9J"


STRIPE_API_KEY_PUBLISHABLE = "pk_test_51HU5jvFAyf8J0IoEy5UYKhklA8eW1XEFtetsBzTaBcWl2Sgw0SHhv4EuOZ1Zk2RZFwKKEAjHicVllCicekv66BVO00alvoahqO"
STRIPE_API_KEY_HIDDEN = "sk_test_51HU5jvFAyf8J0IoEIwXdkhJg7FkubEcGH2SHmK33ZY04989MDkzKCecvavtIOInxdKYKpN6MUrsVxMsIHQ6FYepD00Kz7GgdXY"

RAZORPAY_API_KEY_PUBLISHABLE = "rzp_test_q3wepxuqzC1Gip"
RAZORPAY_API_KEY_HIDDEN = "ZwXFYaOcFyEzUB1gX0D85aYD"

PAYPAL_API_KEY_PUBLISHABLE = "Acj6k32QQTwsGBtMaFrq-DJoe7vp8nXuurQc8mXvtFoqHZ5qMjnzfXPdwrCyMCmXZvZApD-vneXPaZ-x"
PAYPAL_API_KEY_HIDDEN = "EL9_C9VDSAHboJddJBUit1GEMLySx6wGBFVqcTqRttpzGeKnY6epwl3cRwFt3xe02imZp8Zb386upG9J"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')d_79y%ts@j8wc2^&4f4q!6reu$%!4nu#wzwe)v6!6%9aub_(-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# email
EMAIL_HOST = 'smtp.tsdinternationnal.com.vn'
EMAIL_PORT = 587
# end email

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'cart'
LOGOUT_REDIRECT_URL = 'home'

# cart
SESSION_COOKIE_AGE = 86400
CART_SESSION_ID = 'cart'
# end cart

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
    'products',
    'cart',
    'newsletter',
    'order',
    'coupon',
    'userprofile',
    'carousel',
    'supplier'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'products.context_processors.menu_categories',
                'cart.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'myapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static_cdn", "static_root")


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static_cdn", "media_root")