# Generated by Django 3.1.6 on 2021-02-02 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0018_auto_20210130_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 8, 30, 36, 506101)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 8, 30, 36, 506101)),
        ),
    ]
