# Generated by Django 3.1.6 on 2021-02-02 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0019_auto_20210202_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 10, 39, 12, 569994)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 10, 39, 12, 569994)),
        ),
    ]
