# Generated by Django 3.2.1 on 2021-05-13 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0022_auto_20210202_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 13, 53, 13, 768715)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 13, 53, 13, 768715)),
        ),
    ]
